### ISSUE TITLE
Documentation is not consistent on `npm` and `yarn`

### ISSUE THREAD

**Issue by carrieje** [cozy/cozy-konnector-template#19]
`README.md` uses indistinctively `npm` and `yarn` in command line.
I am not enough familiar with these tools and your habits to open a PR to sort this up.
According to what I have read elsewhere, I assume `yarn` should be used everywhere instead of `npm`.

**Comment by doubleface** [comment]
You are right, we tend to use yarn on all of our projects. It allows more consistency in the version of the dependencies.

**Comment by doubleface** [comment]
With bf3316fd24943a1ab7bfb67f6713a717ed463f34 it should be better.
