### ISSUE TITLE
Npm run standalone and npm run dev are not clear in what they do

### ISSUE THREAD

**Issue by doubleface** [cozy/cozy-konnector-template#2]
```npm run standalone``` actually runs the konnector without needing an accessible cozy. Because of the "standalone" name, we could think that it does not need a internet connection

Propositions : ```npm run nocozy``` or ```npm run nostack```

```npm run dev``` actually runs the connector in development mode by logging into the cozy through OAuth authentication, without being installed in the cozy.

Propositions : ```npm run noinstall``` or ```npm run oauth```

**Comment by nicofrand** [comment]
npm run standalone sounds fine to me. I'd expect a connector that fetches things from a website to have access to the internet anyway.
